### ISSUE TITLE
Use overflow-checking built-in functions where available

### ISSUE THREAD

**Issue by jwakely** [PeterSommerlad/PSsimplesafeint#4]
GCC and Clang both provide efficient overflow checks via https://gcc.gnu.org/onlinedocs/gcc/Integer-Overflow-Builtins.html

**Comment by PeterSommerlad** [comment]
for msvc see https://stackoverflow.com/questions/69565333/are-there-overflow-check-math-functions-for-msvc

**Comment by preney** [comment]
If a goal is to detect overflow within ISO C++ while not relying on compiler intrinsics and without triggering the overflow, then see Hacker's Delight, Second Edition ( https://www.informit.com/store/hackers-delight-9780321842688 ) Chapter 2-13 "Overflow Detection" for +, -, *, and /.

**Comment by preney** [comment]
I should clarify Hacker's Delight does not have C++ code in it, rather, it is discussion and some C code. The techniques discussed to handle overflow detection can be easily and appropriately implemented in C++.

**Comment by PeterSommerlad** [comment]
see other repository PSsODIN
